### PR TITLE
German translations to sustainable event resources

### PR DESCRIPTION
**Pull request by Theresia5**
I wasn't able to directly commit these two localized pages to the German branch. - Can you?

### CODE REVIEW

**Review by jennymevents — APPROVED** [review]

**Comment by jennymevents** [comment]
@Theresia5 - please update to have these files merge to the branch de-de-German: https://github.com/jennymevents/sustainable-events/tree/de-de-German. That way it will not overwrite the main repo. Thank you!

**Comment by Theresia5** [comment]
Hi Jenny,

Being an absolute newbie to GitHub: How do I update?

Thanks,

Theresia

**Comment by jennymevents** [comment]
No problem! Change the branch from jennymevents:English to jennymeevents:de-de-German and then resubmit the PR.

Does that make sense?

Jenny Morgan | Senior DevRel Global Event PM Lead
E: ***@***.******@***.***>
T: @jennymevents <https://twitter.com/JennyMEvents>
L: jennymevents<https://www.linkedin.com/in/jennymevents/>
G: GitHub Virtual Events Repo<https://github.com/microsoft/virtual-events>

Emails have a significant impact on the environment. Check out Brief<https://thebrieflab.com/book_brief/> for email writing tips & plant trees<https://plant.ecosia.org/> to offset your CO2 footprint!

**Comment by Theresia5** [comment]
This is what I am looking at now:

***@***.***

Where do I need to click to have the German content integrated?!?

(When I click on “Pull requests” from here, I get to this screen:
***@***.***

And when I click on “New pull request” from here, I get to an option to compare changes.

***@***.***

No clue where to go from here… 😲

**Pull request merged**
